### PR TITLE
New service: get search results instead of queueing them

### PR DESCRIPTION
**Pull request by daniele-athome**
Reissuing #71 because I had to make another PR for another thing and I need the main branch for myself.

### CODE REVIEW

**Comment by bushvin** [comment]
I would like to validate this myself prior to merging, but I will not be able to do that before 26/8

**Comment by daniele-athome** [comment]
Hi there! Hope you're doing well. Any chance you could take a look at this? Thanks.

**Review by bushvin — APPROVED** [review]

**Comment by bushvin** [comment]
merged. I will make a new release asap

**Comment by daniele-athome** [comment]
I forgot to document the new service! I'll open a new PR within a few days.

**Comment by bushvin** [comment]
I already documented some. Feel free to complete the README.md

**Comment by daniele-athome** [comment]
I opened https://github.com/bushvin/hass-integrations/pull/74 with some suggestions.

Thanks for crediting by the way!

**Pull request merged**
